# Render.com deployment configuration
version: 2

services:
  - type: web
    name: habitos-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: habitos-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: habitos-db
    databaseName: habitos
    user: habitos-user
